apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: django
          image: ishijapriyansha/translator
          ports:
            - containerPort: 8000
