apiVersion: v1
kind: Service
metadata:
  name: translator-service
spec:
  selector:
    app: translator   
  ports:
    - protocol: TCP
      port: 80                 
      targetPort: 8000         
  type: LoadBalancer
